### ISSUE TITLE
Compilation instructions?

### ISSUE THREAD

**Issue by maubuz** [sacode387/FlowRun#1]
First of all: Thank you so much for this amazing project! I teach computer science at a college in Montreal and I love the idea of "cross-platform Flowgarithm in the browser".

Would it be possible to provide compilation instructions in the Readme?
I've successfully compiled the demo project and I can serve it with a basic http server. However, I'm not very familiar with Scala and ScalaJS so I'm wondering if I'm missing something.

I mostly followed the instructions from Haoyi's [Hands-on Scala.js](https://www.lihaoyi.com/hands-on-scala-js/#TheCommandLine) and [Multi-project builds](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Multi-project+builds) from scala-sbt.org.

My steps:
```sh
> sbt
sbt:flowrun> project demo
sbt:demo> compile
sbt:demo> fastOptJS
```
The  `sbt:demo> run` command failed in but I was still able to find and serve the files inside `FlowRun/demo/target/web/public/main`

Am I missing anything else? It seems functional.

**Comment by sake92** [comment]
@maujac you're welcome, glad you like it!  
Love to have *any* feedback haha.  
So glad you are using it in your teachings! 🎉 😃 

I've added a new page with instructions: https://github.com/sacode387/FlowRun/blob/master/CONTRIBUTING.md  
Hope it is enough, at least for now.

--- 
The `run` commands is like `nodejs myscript.js`. It runs *a console application* (which we don't have here).  
Here we need just to compile the scala code to JS, so `demo/fastLinkJS` is enough.  
The browser loads the necessary JS code.

---
If you have any other questions please do ask!  
Or if you prefer chat: https://discord.com/channels/955759293259472936/959436265915314236

**Comment by maubuz** [comment]
Thank you very much! The instructions are very clear.
