### ISSUE TITLE
Inconsistency between dashboard and diagrams

### ISSUE THREAD

**Issue by micder** [sacode387/FlowRun#12]
When modifying an existing diagram, some inconsistencies are shown on the dashboard. Moreover the shown diagram is not updated or is an older version.

Starting situation:

<img width="312" alt="image" src="https://github.com/sacode387/FlowRun/assets/3777508/6a98fb37-165a-4a83-9b14-9e63470356c8">
<img width="534" alt="image" src="https://github.com/sacode387/FlowRun/assets/3777508/cda4a162-03e5-41d7-b579-c404d98ec0f1">

Added a new symbol:
<img width="529" alt="image" src="https://github.com/sacode387/FlowRun/assets/3777508/d6d613f4-43f5-4060-b7d2-ee97a8678966">

On the dashboard the "output" message is shown:
<img width="307" alt="image" src="https://github.com/sacode387/FlowRun/assets/3777508/c8e8f07a-8f20-4c10-a933-85541846d45f">

This is the diagram with the default message:
<img width="534" alt="image" src="https://github.com/sacode387/FlowRun/assets/3777508/0a12c92a-831a-4494-be6a-d9edec45f0a4">

**Comment by sake92** [comment]
Thanks for reporting this!

Displaying of the image in Dashboard/Explore needs some time.  
I do it lazily in a background thread, don't want to do it on every letter you change in a program text for example...

---
There are 2 issues besides that one:
- need to add a popup that warns you if program isn't saved when you try to leave that editor page
- need to fix a bug in editor when expression is not complete, it doesnt save it properly..

**Comment by sake92** [comment]
Done
