### ISSUE TITLE
How to import exported programs?

### ISSUE THREAD

**Issue by maubuz** [sacode387/FlowRun#2]
I can export the current diagram to the system's clipboard using both the "Copy Source" and "Copy DOT".
However, how can I import the previously exported program?

Looking at the demo file `index.html`, it looks like the diagram DOT could be "inserted" into the `<div class="flowrun-instance>` and then rendered in the browser (graphviz's magic?). However, I get the impression this would have to happen in the back-end before the page is served.

If there isn't currently a way to import diagrams, what is recommend as the best approach to doing this?
Once again, thank you for sharing this project.

**Comment by sake92** [comment]
You have multiple options (not Graphviz' but Flowrun's "magic" 😛 ):
- inserting a blank editor: https://github.com/sacode387/FlowRun/blob/master/demo/src/main/public/index.html#L109
note that you need `class="flowrun--editable"` to be editable, by default it is not
- insert a prepopulated example https://github.com/sacode387/FlowRun/blob/master/demo/src/main/public/index.html#L114-L116
- instantiate an example dynamically in a web page
I don't have a ready example in this codebase, but you can inspect this page to see how I loaded a solution for exercise: https://flowrun.io/tutorials/basic/hello-world
The  `loadEditor` function is only relevant.  
The whole API can be seen here https://github.com/sacode387/FlowRun/blob/master/core/src/main/scala/dev/sacode/flowrun/FlowRun.scala#L29-L36

---
I probably could've implemented an "Import" button..   
But at [flowrun.io](https://flowrun.io) it's easier to just Fork/Copy an existing program from other people...

**Comment by maubuz** [comment]
Thank you for the answer. I was able to use the 3rd option suggested. It seems like that would be the path to an eventual import button.

While doing so, I noticed that the json object generated by the "Copy Source" button contain strings that the function `loadEditor` can't parse. For example, here is a json segment: `"value":"\"Hello World\""`, when called, `loadEditor` returns `Uncaught SyntaxError: JSON.parse: expected ',' or '}' after property value in object`. Once I changed the json strings to `"value":"\\"Hello World\\""` (extra forward slash, like in your hello-word tutorial) then it loaded perfectly.

Maybe `loadEditor` was never intended to work with the json provided by "Copy Source", but I figure I would let you know since it's almost there 😉

The use case for an "Import" button would be:
- There's a local instance of Flowrun running at the college or Flowrun.io is offline;
- The student works on their code and once they are done they export it;
- The exported code can be submitted as an assignment, or saved locally;
- The teacher can import the code for grading;
- The student can import the code and continue working on it.

I'm happy to discuss it further. During the semester it's hard but I would love to eventually take some time to learn Scala and contribute to the project. Lot's of potential. The Discord link you sent me seems to not send me anywhere.

**Comment by sake92** [comment]
@maujac yeah, I had that issue too, never looked deep into it haha..  

Your suggestions are something I thought about too.  
That functionality would be really useful for teachers.  
Shouldn't be too hard to implement it, hopefully just a few lines. 😃 

Here is a correct invite, maybe that one expired, IDK: https://discord.gg/3fJA6DfHbA  
Sure thing, we can chat there and figure it out. 😉

**Comment by sake92** [comment]
@maujac I have implemented a download/load functionality.  
Let me know if you spot any issues! :)
