### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by sscoffman** [sacode387/FlowRun#3]
There seems to be an issue with the Login feature at https://flowrun.io/
After logging in, I still cannot save a flowchart.

Steps performed:
Created a flowchart.
Clicked Save and was prompted to log in.
Clicked Login link
Selected Google icon
Entered Google login information
Login link remains in upper right of page.
Clicked Save and was prompted to log in.
Attempted to login in again with Google - no response when clicking the G icon.

Great tool!  Would love to use it as an alternative to Flowgorithm for my students.

**Comment by sake92** [comment]
@sscoffman thanks for kind words! ❤️   
The server's clock was not correct, the JWT couldnt be validated.. interesting..  
Anyway, this is fixed now! Thanks for reporting!
